import { Inter, Roboto_Mono } from "next/font/google";
import "./globals.css";
import { Metadata } from "next";

const inter = Inter({
	variable: "--font-inter",
	subsets: ["latin"],
});

const robotoMono = Roboto_Mono({
	variable: "--font-roboto-mono",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "NotesLook",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html
			lang="en"
			className={`${inter.variable} ${robotoMono.variable} antialiased`}>
			<body suppressHydrationWarning={true}>{children}</body>
		</html>
	);
}
